README.md
Fixed wrong hyperlink issue for documentation site
=> README doc website fix

documentation/docs/requirements/features-and-requirements.md
Rewrote the "Functional Requirements" and "Non-Functional Requirements"  Re-categorized the functional and non-functional requirements Rewrote some requirements to be more clear
Re-organized the requirements to be sorted in order of importance
=> Updated features-and-requirements

documentation/docs/requirements/features-and-requirements.md
Added the following requirements:
- Log In/Create Account (Functional)
- Preparations (Functional)
- Gold (Non-Functional)
- Towns (Non-Functional)
- Menus (Non-Functional)
- HUD (Non-Functional)
=> Added Functional and Non-Functional Requirements

documentation/docs/requirements/system-overview.md
Added images back into the Project Abstract. Slightly re-worded some areas so that they fit better with the new requirements
=> Changed System Overview

2D Platformer/Assets/Levels/Level1.unity, 2D Platformer/Assets/Scripts/Movement.cs, 2D Platformer/Assets/Scripts/PlayerStats.cs, 2D Platformer/Assets/Scripts/PlayerStats.cs.meta, 2D Platformer/Assets/Scripts/stats.meta, 2D Platformer/Assets/Scripts/stats/CharacterStat.cs, 2D Platformer/Assets/Scripts/stats/CharacterStat.cs.meta, 2D Platformer/Assets/Scripts/stats/StatModifier.cs, 2D Platformer/Assets/Scripts/stats/StatModifier.cs.meta
Currently only includes health, speed and strength. You can adjust speed with Z and read the speed stat with X, and it will actually adjust your movement speed in game.
=> Added stat sheet for characters which can be referenced by other sprites

documentation/docs/system-architecture/version-control.md
basically just described GitHub
=> Updated Version Control in Design Document

documentation/docs/system-architecture/development-environment.md
Added a development environment description
=> Updated Development Environment Description

documentation/docs/system-architecture/Algorithms.md
=> Alex-Doc-Review

2D Platformer/Assets/Scripts/Level Spawner.cs, 2D Platformer/Assets/Scripts/Level Spawner.cs.meta
Added script for spawning level
=> Added Scripts

2D Platformer/Assets/Levels/ExperienceLevelPrefab.meta, 2D Platformer/Assets/Levels/ExperienceLevelPrefab/Exp_Level Prefab.prefab, 2D Platformer/Assets/Levels/ExperienceLevelPrefab/Exp_Level Prefab.prefab.meta
Contains the scripts for the level and experience as well as the objects.
=> Experience/Level Prefab

2D Platformer/Assets/Levels/MainMenu.unity
Added functionality to the 'play' and 'quit' button so that they open the level generator scene, and quit the game, respectively.
=> Added Button Functionality

2D Platformer/ProjectSettings/EditorBuildSettings.asset
Replaced boss room scene with level generation scene
=> Fixed Scenes in Build

2D Platformer/Assets/Levels/AccountMenu.unity, 2D Platformer/Assets/Scripts/FirebaseController.cs
=> Added UI for Forgot Password and Profile Pages

2D Platformer/Assets/Prefabs/Gary.prefab, 2D Platformer/Assets/Prefabs/Room 10.prefab, 2D Platformer/Assets/Prefabs/Room 11.prefab, 2D Platformer/Assets/Prefabs/Room 12.prefab, 2D Platformer/Assets/Prefabs/Room 13.prefab, 2D Platformer/Assets/Prefabs/Room 14.prefab, 2D Platformer/Assets/Prefabs/Room 2.prefab, 2D Platformer/Assets/Prefabs/Room 4.prefab, 2D Platformer/Assets/Prefabs/Room 6.prefab, 2D Platformer/Assets/Prefabs/Room 8.prefab, 2D Platformer/Assets/Prefabs/Room 9.prefab, 2D Platformer/Assets/Prefabs/Tile.prefab, 2D Platformer/Assets/Prefabs/Tile2.prefab, 2D Platformer/Assets/Prefabs/Tile3.prefab, 2D Platformer/Assets/Prefabs/Wall 1.prefab, 2D Platformer/Assets/Prefabs/Wall 2.prefab
Removed 2d box colliders from the gameobjects in the prefab rooms, and changed the box colliders to edge colliders on the tile blocks.
=> Fixed getting stuck when walking on ground

2D Platformer/Assets/Levels/MainMenu/MainMenu.unity.meta, 2D Platformer/Assets/Photon/FusionAddons/Photon-Fusion-Physics-Addon-2.0.0-RC3-807.unitypackage.meta, 2D Platformer/Assets/Photon/FusionAddons/Photon-Fusion-TestSuit-Addon-2.0.0-RC3-807.unitypackage.meta, 2D Platformer/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.0-RC3-807.unitypackage.meta, 2D Platformer/Assets/Prefabs/Gary.prefab
Changed garys prefab to stop him from spawning in wall
=> Fixed Gary to Spawning on 0,0

2D Platformer/Assets/Prefabs/Gary.prefab, 2D Platformer/Assets/Prefabs/Room 10.prefab, 2D Platformer/Assets/Prefabs/Room 12.prefab, 2D Platformer/Assets/Prefabs/Room 2.prefab, 2D Platformer/Assets/Prefabs/Room 3.prefab, 2D Platformer/Assets/Prefabs/Room 4.prefab, 2D Platformer/Assets/Prefabs/Room 5.prefab, 2D Platformer/Assets/Prefabs/Room 7.prefab, 2D Platformer/Assets/Prefabs/Room 8.prefab, 2D Platformer/Assets/Prefabs/Room 9.prefab
Added blocks to prefabs so that we can easily traverse through the map
=> Added platforms for easy traveling

2D Platformer/Assets/Animations/DamageText 1.controller, 2D Platformer/Assets/Animations/DamageText 1.controller.meta, 2D Platformer/Assets/Animations/DamageText 2.controller, 2D Platformer/Assets/Animations/DamageText 2.controller.meta, 2D Platformer/Assets/Animations/DamageText 3.controller, 2D Platformer/Assets/Animations/DamageText 3.controller.meta, 2D Platformer/Assets/Animations/DamageText.anim, 2D Platformer/Assets/Animations/DamageText.anim.meta, 2D Platformer/Assets/Animations/DamageText.controller, 2D Platformer/Assets/Animations/DamageText.controller.meta, 2D Platformer/Assets/Levels/LevelGenerator.unity, 2D Platformer/Assets/Prefabs/DamageText.prefab, 2D Platformer/Assets/Prefabs/DamageText.prefab.meta, 2D Platformer/Assets/Prefabs/Gary.prefab, 2D Platformer/Assets/Prefabs/Skrake.prefab, 2D Platformer/Assets/Scripts/Hitboxes/Hurtbox.cs
text does not destroy itself and makes clone objects this needs to be fixed
=> Added damage text

2D Platformer/Assets/Levels/MainMenu/MainMenu.unity, 2D Platformer/Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset, 2D Platformer/Assets/Prefabs/Menu/PlayerListItem.prefab, 2D Platformer/Assets/Prefabs/Menu/PlayerListItem.prefab.meta, 2D Platformer/Assets/Scripts/Menu/PlayerListItem.cs, 2D Platformer/Assets/Scripts/Menu/PlayerListItem.cs.meta
As mentioned. There are still some issues with rooms/players not being deleted when a player leaves a room, etc.
=> Created Player Name Item for Lobby

2D Platformer/Assets/Levels/MainMenu/MainMenu.unity, 2D Platformer/Assets/Mirror/Examples/RigidbodyBenchmark/Prefabs/Player Ball.prefab, 2D Platformer/Assets/Photon/FusionAddons/Photon-Fusion-Physics-Addon-2.0.0-RC3-807.unitypackage.meta, 2D Platformer/Assets/Photon/FusionAddons/Photon-Fusion-TestSuit-Addon-2.0.0-RC3-807.unitypackage.meta, 2D Platformer/Assets/Photon/FusionDemos/Photon-Fusion-Intro-Sample-2.0.0-RC3-807.unitypackage.meta, 2D Platformer/Assets/Prefabs/Menu/PlayerListItem.prefab, 2D Platformer/Assets/Scripts/Menu/Launcher.cs, 2D Platformer/Assets/Scripts/Menu/MenuManager.cs, 2D Platformer/Assets/Scripts/Menu/PlayerListItem.cs, 2D Platformer/Assets/Scripts/Menu/RoomListItem.cs
Fixed ghost players/lobbies. Player names are now randomly generated to show in lobby
=> Reg 115 multiplayer lobby UI

2D Platformer/Assets/Levels/MainMenu/MainMenu.unity, 2D Platformer/Assets/Scripts/Menu/QuickMatch.cs, 2D Platformer/Assets/Scripts/Menu/QuickMatch.cs.meta
Now can randomly join a lobby or create a new one if there are none currently using Photon RealTime.
=> Create a "Quick Match" Menu Option

2D Platformer/Assets/Animations/Hurt_Back.anim, 2D Platformer/Assets/Animations/Hurt_Dead_Back.anim, 2D Platformer/Assets/Animations/Hurt_Dead_Front.anim, 2D Platformer/Assets/Animations/Hurt_Front.anim, 2D Platformer/Assets/Prefabs/Omar.prefab, 2D Platformer/Assets/Sprites/omar/Animations/Attack_Charging Lunge 2.anim, 2D Platformer/Assets/Sprites/omar/Animations/Attack_Charging Lunge.anim, 2D Platformer/Assets/Sprites/omar/Animations/Attack_Charging Lunge3.anim, 2D Platformer/Assets/Sprites/omar/Animations/Dead_Back.anim, 2D Platformer/Assets/Sprites/omar/Animations/Dead_Front.anim, 2D Platformer/Assets/Sprites/omar/Animations/Hurt_Back.anim, 2D Platformer/Assets/Sprites/omar/Animations/Hurt_Dead_Back.anim, 2D Platformer/Assets/Sprites/omar/Animations/Hurt_Dead_Front.anim, 2D Platformer/Assets/Sprites/omar/Animations/Hurt_Front.anim, 2D Platformer/Assets/Sprites/omar/Animations/OmarPlayer.controller
- Omar doesn't fall through the floor because his RigidBody is now continuous
- Getting hit now deactivates all hitboxes
- Omar's hurt sprites now display properly
=> Omar doesn't fall through the floor

2D Platformer/Assets/ScriptableObjects/StatsConfig.asset, 2D Platformer/Assets/Scripts/Attacking/PlayerAttack.cs
=> Added a basic growth formula for attacks and set gary's base strength to 1

2D Platformer/Assets/Levels/LevelGenerator.unity, 2D Platformer/Assets/Sprites/skrake/Skrake.controller
Maybe a fix for attack animations not triggering. When resolving merge conflicts, pick the LevelGenerator from my file to see if it works.
=> Potential Animation Fix

2D Platformer/Assets/CharacterSelection.meta, 2D Platformer/Assets/CharacterSelection/Characters.meta, 2D Platformer/Assets/CharacterSelection/Characters/Gary.asset, 2D Platformer/Assets/CharacterSelection/Characters/Gary.asset.meta, 2D Platformer/Assets/CharacterSelection/Characters/Omar.asset, 2D Platformer/Assets/CharacterSelection/Characters/Omar.asset.meta, 2D Platformer/Assets/CharacterSelection/Characters/Stephanie.asset, 2D Platformer/Assets/CharacterSelection/Characters/Stephanie.asset.meta, 2D Platformer/Assets/Levels/LevelGenerator.unity, 2D Platformer/Assets/Material/Player.physicsMaterial2D, 2D Platformer/Assets/Prefabs/GarySelect.prefab, 2D Platformer/Assets/Prefabs/GarySelect.prefab.meta, 2D Platformer/Assets/Prefabs/NetworkPlayer.prefab, 2D Platformer/Assets/Prefabs/NetworkPlayer.prefab.meta, 2D Platformer/Assets/Prefabs/Omar.prefab, 2D Platformer/Assets/Prefabs/OmarSelect.prefab, 2D Platformer/Assets/Prefabs/OmarSelect.prefab.meta, 2D Platformer/Assets/Prefabs/StephanieSelect.prefab, 2D Platformer/Assets/Prefabs/StephanieSelect.prefab.meta, 2D Platformer/Assets/Scripts/Character.cs, 2D Platformer/Assets/Scripts/Character.cs.meta, 2D Platformer/Assets/Scripts/CharacterSelect.cs, 2D Platformer/Assets/Scripts/CharacterSelect.cs.meta, 2D Platformer/Assets/Scripts/Movement.cs, 2D Platformer/Assets/Scripts/Steam.cs, 2D Platformer/Assets/Scripts/myNetworkManager.cs, 2D Platformer/Assets/Scripts/myNetworkManager.cs.meta, 2D Platformer/ProjectSettings/EditorBuildSettings.asset
Characters can now be chosen and played
=> Reg 156 have different types of characters in the game

2D Platformer/Assets/Scripts/Movement.cs
Added  midair jump (you can jump in the  air once before touching the ground)
=> Midair jumping is now real

2D Platformer/Assets/Prefabs/Skrake.prefab, 2D Platformer/Assets/Scripts/Movement.cs, 2D Platformer/Assets/Scripts/stats/PlayerStats.cs, 2D Platformer/Assets/Sprites/omar/Animations/Dead_Back.anim, 2D Platformer/Assets/Sprites/omar/Animations/Dead_Front.anim, 2D Platformer/Assets/Sprites/omar/Animations/OmarPlayer.controller
Player now dies when they run out of health (they don't respawn yet tho)
=> Player dies when they run out of health

2D Platformer/Assets/Prefabs/Room 10.prefab, 2D Platformer/Assets/Prefabs/Room 11.prefab, 2D Platformer/Assets/Prefabs/Room 12.prefab, 2D Platformer/Assets/Prefabs/Room 14.prefab, 2D Platformer/Assets/Prefabs/Room 2.prefab, 2D Platformer/Assets/Prefabs/Room 4.prefab, 2D Platformer/Assets/Prefabs/Room 9.prefab, 2D Platformer/Assets/Scripts/LevelSpawner.cs
Added spawn points to prefabs and added them in the levelspawner script
=> Added more enemy spawn locations

2D Platformer/Assets/Tests/PlayTests/GameplayTests.cs, 2D Platformer/Assets/Tests/PlayTests/GameplayTests.cs.meta, 2D Platformer/Assets/Tests/PlayTests/PhotonTests.cs, 2D Platformer/Assets/Tests/PlayTests/PhotonTests.cs.meta, 2D Platformer/Assets/Tests/PlayTests/PlayTests.asmdef, 2D Platformer/Assets/Tests/PlayTests/ProceduralGenerationTests.cs, 2D Platformer/Assets/Tests/PlayTests/ProceduralGenerationTests.cs.meta
For Photon, Proc Gen, PlayGame
=> Tests Added

documentation/docs/requirements/System-Overview.md, documentation/docs/system-architecture/Algorithms.md, documentation/docs/system-architecture/Version-Control.md
Small Documentation changes. Updated from feedback from TA
=> Brandon c3207 patch 1
